const Images = {
  background: require('../assests/Background.png'),
  logo: require('../assests/Logo.png'),
  faceId: require('../assests/faceId.png'),
  emailIcon: require('../assests/email.png'),
  passwordIcon: require('../assests/Password.png'),
  lockIcon: require('../assests/lock.png'),
  keyIcon: require('../assests/key.png'),
  confirmPasswordIcon: require('../assests/confirmPassword.png'),
  HomeIcon: require('../assests/home1.png'),
  HomeFilledIcon: require('../assests/home2.png'),
  ProfileIcon: require('../assests/profile1.png'),
  ProfileFilledIcon: require('../assests/profile2.png'),
  LogoutIcon: require('../assests/logout.png'),
  ItemImage: require('../assests/FlightImg.png'),
  flightIcon: require('../assests/flight.png'),
  inprogressFlightIcon: require('../assests/inprogessFlight.png'),
  EditIcon: require('../assests/edit.png'),
  ForwordIcon: require('../assests/forword.png'),
  BackIcon: require('../assests/back.png'),
  inprogressFlightImg: require('../assests/inprogressFlight.png'),
  AirplaneImg: require('../assests/Airplane.png'),
  CameraIcon: require('../assests/camera.png'),
  PictureIcon: require('../assests/PictureIcon.png'),
  time: require('../assests/time.png'),
  calander: require('../assests/calander.png'),
};

export default Images;
